// <auto-generated />
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200112110119_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("ApplicationCore.Entities.user", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("activated")
                        .HasColumnType("int(10)");

                    b.Property<int>("created")
                        .HasColumnType("int(10)");

                    b.Property<string>("group")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("mail")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("nickName")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("password")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("url")
                        .HasColumnType("varchar(150)");

                    b.HasKey("id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
